--select * from EQUIP_STATUS_CODE
--select * from MATERIAL_BLEND
DECLARE @CURRENTLY_IDENT INT;
SET  @CURRENTLY_IDENT = CASE WHEN (DATEPART(HH, GETDATE()) BETWEEN 8 AND 19) THEN 1 ELSE 2 END;
select @CURRENTLY_IDENT, GETUTCDATE()-4, GETDATE()


SELECT GETDATE()


SELECT 
CONVERT(datetime, 
SWITCHOFFSET(CONVERT(DATETIMEOFFSET, GETUTCDATE()), 
DATENAME(TZOFFSET, SYSDATETIMEOFFSET()))) 
AS LOCAL_IST;

select * from sys.time_zone_info;

declare @utc_date datetime = getdate()
select @utc_date as utc_time_zone, 
  dateadd(hh, datediff(hh, getutcdate(), getdate()), @utc_date) as local_time_zone


SELECT 
	HC.DUMP_END_SHIFT_DATE,
	--HC.SHI
	--HC.DUMP_END_SHIFT_IDENT,
	HC.LOAD_START_SHIFT_IDENT TURNO,
	SUM(HC.QUANTITY_REPORTING) QUANTITY 
	--1 NUM_LOADS, 
	--HC.MATERIAL_IDENT, 
	--M.MAT_DESC MATERIAL_DESC, 
	--M.MAT_MATERIAL_GROUP MATERIAL_TYPE,
	--MT.DESCRIP MATERIAL_TYPE_DESC
FROM 
	HAUL_CYCLE_TRANS HC 
	--INNER JOIN (SELECT * FROM EQUIP WHERE TEST = 'N') HAULERS ON HC.HAULING_UNIT_IDENT = HAULERS.EQUIP_IDENT 
	--INNER JOIN (SELECT * FROM EQUIP WHERE TEST = 'N') LOADERS ON HC.LOADING_UNIT_IDENT = LOADERS.EQUIP_IDENT 
	--LEFT OUTER JOIN LOCATION_PARENT L ON HC.LOAD_LOCATION_SNAME = L.LOCATION_SNAME 
	--LEFT OUTER JOIN 
		--MATERIAL M INNER JOIN MATERIAL_TYPE MT ON M.MAT_MATERIAL_GROUP = MT.MAT_TYPE
	--ON HC.MATERIAL_IDENT = M.MAT_MATERIAL_IDENT
	WHERE CAST(HC.DUMP_END_SHIFT_DATE AS DATE) = CAST(GETDATE() AS date) --Selecciona fecha actual
		AND HC.LOAD_START_SHIFT_IDENT

SELECT * FROM HAUL_CYCLE_TRANS WHERE HC.DUMP_START_SHIFT_IDENT = @CURRENTLY_IDENT
select * from EQUIP