/**DD: Modelo de tiempos por categorías**/
select 
	FLT.FLT_DESC
	,EQ.EQP_TYPE 
	,EQT.DESCRIP
	,EQ.NAME
	,Shift_date
	,Shift_ident
	,Start_timestamp
	,End_timeStamp
	,Segundos = DATEDIFF(second, Start_timestamp, End_timeStamp) 
	,Minutos = DATEDIFF(second, Start_timestamp, End_timeStamp) / 60.00
	,DHMS = DATEDIFF(second, Start_timestamp, End_timeStamp) / 3600.00 / 24.0 
	,EST.Equip_Ident
	,ESC.STATUS_CODE
	,ESC.STATUS_DESC
	,EST.SUB_STATUS_CODE
	,SSC.SUB_STATUS_DESC
	,scc.STATUSCAT_CODE CATEGORIA
	,st.DESCRIP CATEGORIA_DESC
	,scc.STATUS_CODE CODIGO_ESTADO
	,ESC.STATUS_DESC CODIGO_DESC

from equipment_status_trans EST
	INNER JOIN EQUIP EQ ON EQ.EQUIP_IDENT = EST.EQUIP_IDENT
	INNER JOIN EQUIP_TYPE EQT  ON  EQ.EQP_TYPE = EQT.EQTYPE_IDENT 
	INNER JOIN FLEET FLT ON FLT.FLT_FLEET_IDENT = EQ.FLEET_IDENT
	INNER JOIN EQUIP_STATUS_CODE ESC ON EST.STATUS_CODE = ESC.STATUS_CODE 
	LEFT JOIN EQUIP_SUB_STATUS_CODE SSC ON SSC.SUB_STATUS_CODE =EST.SUB_STATUS_CODE
	INNER JOIN STATUS_CODE_CATEGORY SCC  ON SCC.STATUS_CODE = ESC.STATUS_CODE
	INNER JOIN STATUS_CATEGORY ST ON SCC.STATUSCAT_CODE = ST.STATUSCAT_CODE

where Shift_date = '2022-04-11' and EST.Equip_ident= 'T001'
	AND SCC.STATUSCAT_CODE  IN('PROD','NO_PROD','DEM_OP','RES_OPER','RES_EXT','NO_PROG','DOWN_P','DOWN_NP')
	AND ESC.ACTIVE = 'Y'


/**DD: Estado de equipos con su respectiva categoría**/
select 
	eq.equip_ident,
	eq.name,
	eq.fleet_ident,
	fl.flt_desc,
	ces.STATUS_CODE,
	esc.status_desc,
	ST.DESCRIP ESTADO

FROM current_Equip_status CES 
	INNER JOIN EQUIP_STATUS_CODE  ESC on CES.STATUS_CODE = ESC.STATUS_CODE 
	INNER JOIN EQUIP EQ on eq.equip_ident = CES.equip_ident 
	INNER JOIN FLEET FL on FL.flt_fleet_ident = eq.fleet_ident
	iNNER JOIN STATUS_CODE_CATEGORY SCC  ON ESC.STATUS_CODE = SCC.STATUS_CODE
	INNER JOIN STATUS_CATEGORY ST ON SCC.STATUSCAT_CODE = ST.STATUSCAT_CODE

where SCC.STATUSCAT_CODE  IN('PROD','NO_PROD','DEM_OP','RES_OPER','RES_EXT','NO_PROG','DOWN_P','DOWN_NP')
	AND EQ.ACTIVE = 'Y' 




select 
	--eq.fleet_ident FLOTA,
	fl.flt_desc FLOTA,
	ESTADO = CASE WHEN (ST.DESCRIP = 'Reservas Operativas' OR ST.DESCRIP = 'Reservas Externas') THEN 'Reservas' ELSE ST.DESCRIP END,
	ST.DESCRIP ESTADO,
	COUNT(eq.equip_ident) CANTIDAD
FROM current_Equip_status CES 
	INNER JOIN EQUIP_STATUS_CODE  ESC on CES.STATUS_CODE = ESC.STATUS_CODE 
	INNER JOIN EQUIP EQ on eq.equip_ident = CES.equip_ident 
	INNER JOIN FLEET FL on FL.flt_fleet_ident = eq.fleet_ident
	iNNER JOIN STATUS_CODE_CATEGORY SCC  ON ESC.STATUS_CODE = SCC.STATUS_CODE
	INNER JOIN STATUS_CATEGORY ST ON SCC.STATUSCAT_CODE = ST.STATUSCAT_CODE
where 
SCC.STATUSCAT_CODE IN('PROD','NO_PROD','DEM_OP','RES_OPER','RES_EXT','NO_PROG','DOWN_P','DOWN_NP')
		AND (FLT_DESC = 'CAMIONES')
AND EQ.ACTIVE = 'Y'
GROUP BY eq.FLEET_IDENT, fl.FLT_DESC, st.DESCRIP



select DATEADD(hh, 0, getDate()), GETDATE()
select CONVERT(char(10), GETDATE(), 101)