
/**ESTADO de PALAS**/
--1. E822
select
	getdate() 'CURRENT_DATE',
	CES.TIMESTAMP 'TIMESTAMP',
	EQ.NAME FLEET,
	FL.FLT_DESC DESCRIPTION,
	STATUS = CASE WHEN (ST.DESCRIP = 'Reservas Operativas' OR ST.DESCRIP = 'Reservas Externas') THEN 'Reservas' ELSE ST.DESCRIP END
FROM current_Equip_status CES 
	INNER JOIN EQUIP_STATUS_CODE ESC on CES.STATUS_CODE = ESC.STATUS_CODE 
	INNER JOIN EQUIP EQ on eq.equip_ident = CES.equip_ident 
	INNER JOIN FLEET FL on FL.flt_fleet_ident = eq.fleet_ident
	iNNER JOIN STATUS_CODE_CATEGORY SCC  ON ESC.STATUS_CODE = SCC.STATUS_CODE
	INNER JOIN STATUS_CATEGORY ST ON SCC.STATUSCAT_CODE = ST.STATUSCAT_CODE
where SCC.STATUSCAT_CODE IN('PROD','NO_PROD','DEM_OP','RES_OPER','RES_EXT','NO_PROG','DOWN_P','DOWN_NP')
	AND EQ.ACTIVE = 'Y' AND eq.EQUIP_IDENT = 'E822'

--2. E838
select
	getdate() 'CURRENT_DATE',
	CES.TIMESTAMP 'TIMESTAMP',
	EQ.NAME FLEET,
	FL.FLT_DESC DESCRIPTION,
	STATUS = CASE WHEN (ST.DESCRIP = 'Reservas Operativas' OR ST.DESCRIP = 'Reservas Externas') THEN 'Reservas' ELSE ST.DESCRIP END
FROM current_Equip_status CES 
	INNER JOIN EQUIP_STATUS_CODE ESC on CES.STATUS_CODE = ESC.STATUS_CODE 
	INNER JOIN EQUIP EQ on eq.equip_ident = CES.equip_ident 
	INNER JOIN FLEET FL on FL.flt_fleet_ident = eq.fleet_ident
	iNNER JOIN STATUS_CODE_CATEGORY SCC  ON ESC.STATUS_CODE = SCC.STATUS_CODE
	INNER JOIN STATUS_CATEGORY ST ON SCC.STATUSCAT_CODE = ST.STATUSCAT_CODE
where SCC.STATUSCAT_CODE IN('PROD','NO_PROD','DEM_OP','RES_OPER','RES_EXT','NO_PROG','DOWN_P','DOWN_NP')
	AND EQ.ACTIVE = 'Y' AND eq.EQUIP_IDENT = 'E838'


/**ESTADO de CARGADORES**/
--1. C821
select
	getdate() 'CURRENT_DATE',
	CES.TIMESTAMP 'TIMESTAMP',
	EQ.NAME FLEET,
	FL.FLT_DESC DESCRIPTION,
	STATUS = CASE WHEN (ST.DESCRIP = 'Reservas Operativas' OR ST.DESCRIP = 'Reservas Externas') THEN 'Reservas' ELSE ST.DESCRIP END
FROM current_Equip_status CES 
	INNER JOIN EQUIP_STATUS_CODE ESC on CES.STATUS_CODE = ESC.STATUS_CODE 
	INNER JOIN EQUIP EQ on eq.equip_ident = CES.equip_ident 
	INNER JOIN FLEET FL on FL.flt_fleet_ident = eq.fleet_ident
	iNNER JOIN STATUS_CODE_CATEGORY SCC  ON ESC.STATUS_CODE = SCC.STATUS_CODE
	INNER JOIN STATUS_CATEGORY ST ON SCC.STATUSCAT_CODE = ST.STATUSCAT_CODE
where SCC.STATUSCAT_CODE IN('PROD','NO_PROD','DEM_OP','RES_OPER','RES_EXT','NO_PROG','DOWN_P','DOWN_NP')
	AND EQ.ACTIVE = 'Y' AND eq.EQUIP_IDENT = 'C821'

--2. C769
select
	getdate() 'CURRENT_DATE',
	CES.TIMESTAMP 'TIMESTAMP',
	EQ.NAME FLEET,
	FL.FLT_DESC DESCRIPTION,
	STATUS = CASE WHEN (ST.DESCRIP = 'Reservas Operativas' OR ST.DESCRIP = 'Reservas Externas') THEN 'Reservas' ELSE ST.DESCRIP END
FROM current_Equip_status CES 
	INNER JOIN EQUIP_STATUS_CODE ESC on CES.STATUS_CODE = ESC.STATUS_CODE 
	INNER JOIN EQUIP EQ on eq.equip_ident = CES.equip_ident 
	INNER JOIN FLEET FL on FL.flt_fleet_ident = eq.fleet_ident
	iNNER JOIN STATUS_CODE_CATEGORY SCC  ON ESC.STATUS_CODE = SCC.STATUS_CODE
	INNER JOIN STATUS_CATEGORY ST ON SCC.STATUSCAT_CODE = ST.STATUSCAT_CODE
where SCC.STATUSCAT_CODE IN('PROD','NO_PROD','DEM_OP','RES_OPER','RES_EXT','NO_PROG','DOWN_P','DOWN_NP')
	AND EQ.ACTIVE = 'Y' AND eq.EQUIP_IDENT = 'C769'

--2. C835
select
	getdate() 'CURRENT_DATE',
	CES.TIMESTAMP 'TIMESTAMP',
	EQ.NAME FLEET,
	FL.FLT_DESC DESCRIPTION,
	STATUS = CASE WHEN (ST.DESCRIP = 'Reservas Operativas' OR ST.DESCRIP = 'Reservas Externas') THEN 'Reservas' ELSE ST.DESCRIP END
FROM current_Equip_status CES 
	INNER JOIN EQUIP_STATUS_CODE ESC on CES.STATUS_CODE = ESC.STATUS_CODE 
	INNER JOIN EQUIP EQ on eq.equip_ident = CES.equip_ident 
	INNER JOIN FLEET FL on FL.flt_fleet_ident = eq.fleet_ident
	iNNER JOIN STATUS_CODE_CATEGORY SCC  ON ESC.STATUS_CODE = SCC.STATUS_CODE
	INNER JOIN STATUS_CATEGORY ST ON SCC.STATUSCAT_CODE = ST.STATUSCAT_CODE
where SCC.STATUSCAT_CODE IN('PROD','NO_PROD','DEM_OP','RES_OPER','RES_EXT','NO_PROG','DOWN_P','DOWN_NP')
	AND EQ.ACTIVE = 'Y' AND eq.EQUIP_IDENT = 'C835'

/**ESTADO de CAMIONES**/
select
	GETDATE() 'CURRENT_TIMESTAMP',
	fl.flt_desc FLEET,
	STATUS = CASE WHEN (ST.DESCRIP = 'Reservas Operativas' OR ST.DESCRIP = 'Reservas Externas') THEN 'Reservas' ELSE ST.DESCRIP END,
	COUNT(eq.equip_ident) QUANTITY
FROM current_Equip_status CES 
	INNER JOIN EQUIP_STATUS_CODE  ESC on CES.STATUS_CODE = ESC.STATUS_CODE 
	INNER JOIN EQUIP EQ on eq.equip_ident = CES.equip_ident 
	INNER JOIN FLEET FL on FL.flt_fleet_ident = eq.fleet_ident
	iNNER JOIN STATUS_CODE_CATEGORY SCC  ON ESC.STATUS_CODE = SCC.STATUS_CODE
	INNER JOIN STATUS_CATEGORY ST ON SCC.STATUSCAT_CODE = ST.STATUSCAT_CODE
where SCC.STATUSCAT_CODE  IN('PROD','NO_PROD','DEM_OP','RES_OPER','RES_EXT','NO_PROG','DOWN_P','DOWN_NP')
		AND (FLT_DESC = 'CAMIONES')
AND EQ.ACTIVE = 'Y'
GROUP BY eq.FLEET_IDENT, fl.FLT_DESC, st.DESCRIP


/**Tiempo de manteniento no programado de la pala**/
--E822
DECLARE @CURRENTLY_IDENT INT;
DECLARE @CSHIFT_DATE DATE;
SET  @CURRENTLY_IDENT = 
	CASE WHEN (DATEPART(HH, GETDATE()) BETWEEN 8 AND 19) THEN 1 ELSE 2 END;
SET @CSHIFT_DATE = 
	CASE WHEN (@CURRENTLY_IDENT = 2 AND (DATEPART(HH, GETDATE()) BETWEEN 0 AND 7)) 
	THEN CONVERT(date, dateadd(DD,-1,GETDATE()))
	ELSE CONVERT(date, GETDATE()) END;
SELECT
	GETDATE() 'CURRENT_TIMESTAMP',
	START_TIMESTAMP,
	'END_TIMESTAMP' = CASE WHEN (END_TIMESTAMP IS NULL) THEN 'ON GOING' ELSE END_TIMESTAMP END,
	SHIFT_DATE,
	SHIFT_IDENT,
	'E822' EQUIP_IDENT,
	'M02' STATUS_CODE,
	'Mantenimiento No Programado' STATUS,
	HOURS =
		(CASE WHEN END_TIMESTAMP IS NULL THEN (DATEDIFF(HOUR,START_TIMESTAMP,GETDATE()))
		ELSE (DATEDIFF(SECOND,START_TIMESTAMP,END_TIMESTAMP)) END ) / 3600.0
FROM EQUIPMENT_STATUS_TRANS
WHERE STATUS_CODE = 'M02' AND EQUIP_IDENT = 'E822'
	--AND SHIFT_IDENT = @CURRENTLY_IDENT	--turno en el que se consulta
	--AND SHIFT_DATE = @CSHIFT_DATE		--fecha segun el turno en el que se consulta si  
GROUP BY START_TIMESTAMP, END_TIMESTAMP, SHIFT_DATE, SHIFT_IDENT

--E838
DECLARE @CURRENTLY_IDENT INT;
DECLARE @CSHIFT_DATE DATE;
SET  @CURRENTLY_IDENT = 
	CASE WHEN (DATEPART(HH, GETDATE()) BETWEEN 8 AND 19) THEN 1 ELSE 2 END;
SET @CSHIFT_DATE = 
	CASE WHEN (@CURRENTLY_IDENT = 2 AND (DATEPART(HH, GETDATE()) BETWEEN 0 AND 7)) 
	THEN CONVERT(date, dateadd(DD,-1,GETDATE()))
	ELSE CONVERT(date, GETDATE()) END;
SELECT
	GETDATE() 'CURRENT_TIMESTAMP',
	START_TIMESTAMP,
	'END_TIMESTAMP' = CASE WHEN (END_TIMESTAMP IS NULL) THEN 'ON GOING' ELSE END_TIMESTAMP END,
	SHIFT_DATE,
	SHIFT_IDENT,
	'E838' EQUIP_IDENT,
	'M02' STATUS_CODE,
	'Mantenimiento No Programado' STATUS,
	HOURS =
		(CASE WHEN END_TIMESTAMP IS NULL THEN (DATEDIFF(HOUR,START_TIMESTAMP,GETDATE()))
		ELSE (DATEDIFF(SECOND,START_TIMESTAMP,END_TIMESTAMP)) END ) / 3600.0
FROM EQUIPMENT_STATUS_TRANS
WHERE STATUS_CODE = 'M02' AND EQUIP_IDENT = 'E838'
	--AND SHIFT_IDENT = @CURRENTLY_IDENT	--turno en el que se consulta
	--AND SHIFT_DATE = @CSHIFT_DATE		--fecha segun el turno en el que se consulta si  
GROUP BY START_TIMESTAMP, END_TIMESTAMP, SHIFT_DATE, SHIFT_IDENT


/**Tiempo de manteniento no programado deL CARGADOR**/
--C769
DECLARE @CURRENTLY_IDENT INT;
DECLARE @CSHIFT_DATE DATE;
SET  @CURRENTLY_IDENT = 
	CASE WHEN (DATEPART(HH, GETDATE()) BETWEEN 8 AND 19) THEN 1 ELSE 2 END;
SET @CSHIFT_DATE = 
	CASE WHEN (@CURRENTLY_IDENT = 2 AND (DATEPART(HH, GETDATE()) BETWEEN 0 AND 7)) 
	THEN CONVERT(date, dateadd(DD,-1,GETDATE()))
	ELSE CONVERT(date, GETDATE()) END;
SELECT
	GETDATE() 'CURRENT_TIMESTAMP',
	START_TIMESTAMP,
	'END_TIMESTAMP' = CASE WHEN (END_TIMESTAMP IS NULL) THEN 'ON GOING' ELSE END_TIMESTAMP END,
	SHIFT_DATE,
	SHIFT_IDENT,
	'C769' EQUIP_IDENT,
	'M02' STATUS_CODE,
	'Mantenimiento No Programado' STATUS,
	HOURS =
		(CASE WHEN END_TIMESTAMP IS NULL THEN (DATEDIFF(HOUR,START_TIMESTAMP,GETDATE()))
		ELSE (DATEDIFF(SECOND,START_TIMESTAMP,END_TIMESTAMP)) END ) / 3600.0
FROM EQUIPMENT_STATUS_TRANS
WHERE STATUS_CODE = 'M02' AND EQUIP_IDENT = 'C769'
	--AND SHIFT_IDENT = @CURRENTLY_IDENT	--turno en el que se consulta
	--AND SHIFT_DATE = @CSHIFT_DATE		--fecha segun el turno en el que se consulta si  
GROUP BY START_TIMESTAMP, END_TIMESTAMP, SHIFT_DATE, SHIFT_IDENT

--C821
DECLARE @CURRENTLY_IDENT INT;
DECLARE @CSHIFT_DATE DATE;
SET  @CURRENTLY_IDENT = 
	CASE WHEN (DATEPART(HH, GETDATE()) BETWEEN 8 AND 19) THEN 1 ELSE 2 END;
SET @CSHIFT_DATE = 
	CASE WHEN (@CURRENTLY_IDENT = 2 AND (DATEPART(HH, GETDATE()) BETWEEN 0 AND 7)) 
	THEN CONVERT(date, dateadd(DD,-1,GETDATE()))
	ELSE CONVERT(date, GETDATE()) END;
SELECT
	GETDATE() 'CURRENT_TIMESTAMP',
	START_TIMESTAMP,
	'END_TIMESTAMP' = CASE WHEN (END_TIMESTAMP IS NULL) THEN 'ON GOING' ELSE END_TIMESTAMP END,
	SHIFT_DATE,
	SHIFT_IDENT,
	'C821' EQUIP_IDENT,
	'M02' STATUS_CODE,
	'Mantenimiento No Programado' STATUS,
	HOURS =
		(CASE WHEN END_TIMESTAMP IS NULL THEN (DATEDIFF(HOUR,START_TIMESTAMP,GETDATE()))
		ELSE (DATEDIFF(SECOND,START_TIMESTAMP,END_TIMESTAMP)) END ) / 3600.0
FROM EQUIPMENT_STATUS_TRANS
WHERE STATUS_CODE = 'M02' AND EQUIP_IDENT = 'C821'
	--AND SHIFT_IDENT = @CURRENTLY_IDENT	--turno en el que se consulta
	--AND SHIFT_DATE = @CSHIFT_DATE		--fecha segun el turno en el que se consulta si  
GROUP BY START_TIMESTAMP, END_TIMESTAMP, SHIFT_DATE, SHIFT_IDENT

--C835
DECLARE @CURRENTLY_IDENT INT;
DECLARE @CSHIFT_DATE DATE;
SET  @CURRENTLY_IDENT = 
	CASE WHEN (DATEPART(HH, GETDATE()) BETWEEN 8 AND 19) THEN 1 ELSE 2 END;
SET @CSHIFT_DATE = 
	CASE WHEN (@CURRENTLY_IDENT = 2 AND (DATEPART(HH, GETDATE()) BETWEEN 0 AND 7)) 
	THEN CONVERT(date, dateadd(DD,-1,GETDATE()))
	ELSE CONVERT(date, GETDATE()) END;
SELECT
	GETDATE() 'CURRENT_TIMESTAMP',
	START_TIMESTAMP,
	'END_TIMESTAMP' = CASE WHEN (END_TIMESTAMP IS NULL) THEN 'ON GOING' ELSE END_TIMESTAMP END,
	SHIFT_DATE,
	SHIFT_IDENT,
	'C835' EQUIP_IDENT,
	'M02' STATUS_CODE,
	'Mantenimiento No Programado' STATUS,
	HOURS =
		(CASE WHEN END_TIMESTAMP IS NULL THEN (DATEDIFF(HOUR,START_TIMESTAMP,GETDATE()))
		ELSE (DATEDIFF(SECOND,START_TIMESTAMP,END_TIMESTAMP)) END ) / 3600.0
FROM EQUIPMENT_STATUS_TRANS
WHERE STATUS_CODE = 'M02' AND EQUIP_IDENT = 'C835'
	--AND SHIFT_IDENT = @CURRENTLY_IDENT	--turno en el que se consulta
	--AND SHIFT_DATE = @CSHIFT_DATE		--fecha segun el turno en el que se consulta si  
GROUP BY START_TIMESTAMP, END_TIMESTAMP, SHIFT_DATE, SHIFT_IDENT


/**Ubicación de la pala E822**/
DECLARE @CURRENTLY_IDENT INT;
DECLARE @CSHIFT_DATE DATE;
SET  @CURRENTLY_IDENT = 
	CASE WHEN (DATEPART(HH, GETDATE()) BETWEEN 8 AND 19) THEN 1 ELSE 2 END;
SET @CSHIFT_DATE = 
	CASE WHEN (@CURRENTLY_IDENT = 2 AND (DATEPART(HH, GETDATE()) BETWEEN 0 AND 7)) 
	THEN CONVERT(date, dateadd(DD,-1,GETDATE()))
	ELSE CONVERT(date, GETDATE()) END;
SELECT
	GETDATE() 'CURRENT_TIMESTAMP',
	SHIFT_DATE, 
	SHIFT_IDENT, 
	'E822' EQUIP_IDENT,
	LOCATION_NAME
FROM 
	EQUIP_LOCATION_TRANS ELT 
WHERE EQUIP_IDENT = 'E822'
	--AND SHIFT_IDENT = @CURRENTLY_IDENT	--turno en el que se consulta
	--AND SHIFT_DATE = @CSHIFT_DATE			--fecha segun el turno en el que se consulta si
GROUP BY SHIFT_DATE, SHIFT_IDENT, LOCATION_NAME
ORDER BY SHIFT_DATE


/**Ubicación de la pala E838**/
DECLARE @CURRENTLY_IDENT INT;
DECLARE @CSHIFT_DATE DATE;
SET  @CURRENTLY_IDENT = 
	CASE WHEN (DATEPART(HH, GETDATE()) BETWEEN 8 AND 19) THEN 1 ELSE 2 END;
SET @CSHIFT_DATE = 
	CASE WHEN (@CURRENTLY_IDENT = 2 AND (DATEPART(HH, GETDATE()) BETWEEN 0 AND 7)) 
	THEN CONVERT(date, dateadd(DD,-1,GETDATE()))
	ELSE CONVERT(date, GETDATE()) END;
SELECT
	GETDATE() 'CURRENT_TIMESTAMP',
	SHIFT_DATE, 
	SHIFT_IDENT, 
	'E838' EQUIP_IDENT,
	LOCATION_NAME
FROM 
	EQUIP_LOCATION_TRANS ELT 
WHERE EQUIP_IDENT = 'E838'
	--AND SHIFT_IDENT = @CURRENTLY_IDENT	--turno en el que se consulta
	--AND SHIFT_DATE = @CSHIFT_DATE			--fecha segun el turno en el que se consulta si
GROUP BY SHIFT_DATE, SHIFT_IDENT, LOCATION_NAME
ORDER BY SHIFT_DATE


/**Ubicación del cargador C769**/
DECLARE @CURRENTLY_IDENT INT;
DECLARE @CSHIFT_DATE DATE;
SET  @CURRENTLY_IDENT = 
	CASE WHEN (DATEPART(HH, GETDATE()) BETWEEN 8 AND 19) THEN 1 ELSE 2 END;
SET @CSHIFT_DATE = 
	CASE WHEN (@CURRENTLY_IDENT = 2 AND (DATEPART(HH, GETDATE()) BETWEEN 0 AND 7)) 
	THEN CONVERT(date, dateadd(DD,-1,GETDATE()))
	ELSE CONVERT(date, GETDATE()) END;
SELECT
	GETDATE() 'CURRENT_TIMESTAMP',
	SHIFT_DATE, 
	SHIFT_IDENT, 
	'C769' EQUIP_IDENT,
	LOCATION_NAME
FROM 
	EQUIP_LOCATION_TRANS ELT 
WHERE EQUIP_IDENT = 'C769'
	--AND SHIFT_IDENT = @CURRENTLY_IDENT	--turno en el que se consulta
	--AND SHIFT_DATE = @CSHIFT_DATE			--fecha segun el turno en el que se consulta si
GROUP BY SHIFT_DATE, SHIFT_IDENT, LOCATION_NAME
ORDER BY SHIFT_DATE

select * from LOCATION

/**Ubicación del cargador C821**/
DECLARE @CURRENTLY_IDENT INT;
DECLARE @CSHIFT_DATE DATE;
SET  @CURRENTLY_IDENT = 
	CASE WHEN (DATEPART(HH, GETDATE()) BETWEEN 8 AND 19) THEN 1 ELSE 2 END;
SET @CSHIFT_DATE = 
	CASE WHEN (@CURRENTLY_IDENT = 2 AND (DATEPART(HH, GETDATE()) BETWEEN 0 AND 7)) 
	THEN CONVERT(date, dateadd(DD,-1,GETDATE()))
	ELSE CONVERT(date, GETDATE()) END;
SELECT
	GETDATE() 'CURRENT_TIMESTAMP',
	SHIFT_DATE, 
	SHIFT_IDENT, 
	'C821' EQUIP_IDENT,
	LOCATION_NAME
FROM 
	EQUIP_LOCATION_TRANS ELT 
WHERE EQUIP_IDENT = 'C821'
	--AND SHIFT_IDENT = @CURRENTLY_IDENT	--turno en el que se consulta
	--AND SHIFT_DATE = @CSHIFT_DATE			--fecha segun el turno en el que se consulta si
GROUP BY SHIFT_DATE, SHIFT_IDENT, LOCATION_NAME
ORDER BY SHIFT_DATE


/**Ubicación del cargador C835**/
DECLARE @CURRENTLY_IDENT INT;
DECLARE @CSHIFT_DATE DATE;
SET  @CURRENTLY_IDENT = 
	CASE WHEN (DATEPART(HH, GETDATE()) BETWEEN 8 AND 19) THEN 1 ELSE 2 END;
SET @CSHIFT_DATE = 
	CASE WHEN (@CURRENTLY_IDENT = 2 AND (DATEPART(HH, GETDATE()) BETWEEN 0 AND 7)) 
	THEN CONVERT(date, dateadd(DD,-1,GETDATE()))
	ELSE CONVERT(date, GETDATE()) END;
SELECT
	GETDATE() 'CURRENT_TIMESTAMP',
	SHIFT_DATE, 
	SHIFT_IDENT, 
	'C835' EQUIP_IDENT,
	LOCATION_NAME
FROM 
	EQUIP_LOCATION_TRANS ELT 
WHERE EQUIP_IDENT = 'C835'
	--AND SHIFT_IDENT = @CURRENTLY_IDENT	--turno en el que se consulta
	--AND SHIFT_DATE = @CSHIFT_DATE			--fecha segun el turno en el que se consulta si
GROUP BY SHIFT_DATE, SHIFT_IDENT, LOCATION_NAME
ORDER BY SHIFT_DATE


/**Número de camiones en colación**/
select
	GETDATE() 'CURRENT_TIMESTAMP',
	'CAMIONES' FLEET,
	'O02' STATUS_CODE,
	'Colación' DESCRIPTION,
	 COUNT(eq.equip_ident) QUANTITY
FROM current_Equip_status CES 
	INNER JOIN EQUIP EQ on eq.equip_ident = CES.equip_ident 
	INNER JOIN FLEET FL on FL.flt_fleet_ident = eq.fleet_ident
where CES.STATUS_CODE = 'O02' AND fl.FLT_DESC = 'CAMIONES'


/**Número de camiones sin operador**/
select
	GETDATE() 'CURRENT_TIMESTAMP',
	'CAMIONES' FLEET,
	'S01' STATUS_CODE,
	'Sin Operador' DESCRIPTION,
	 COUNT(eq.equip_ident) QUANTITY
FROM current_Equip_status CES 
	INNER JOIN EQUIP EQ on eq.equip_ident = CES.equip_ident 
	INNER JOIN FLEET FL on FL.flt_fleet_ident = eq.fleet_ident
where CES.STATUS_CODE = 'S01' AND fl.FLT_DESC = 'CAMIONES'


/**Número de camiones vacios**/
select 
	GETDATE() 'CURRENT_TIMESTAMP',
	'CAMIONES' FLEET,
	'S01' STATUS_CODE,
	'Sin Operador' DESCRIPTION,
	 COUNT(eq.equip_ident) QUANTITY
FROM current_Equip_status CES 
	INNER JOIN EQUIP EQ on eq.equip_ident = CES.equip_ident 
	INNER JOIN FLEET FL on FL.flt_fleet_ident = eq.fleet_ident
where CES.STATUS_CODE = 'S01' AND fl.FLT_DESC = 'CAMIONES'


/**Número de camiones en carga de combustible**/
select 
	GETDATE() 'CURRENT_TIMESTAMP',
	'CAMIONES' FLEET,
	'O04' STATUS_CODE,
	'Combustible' DESCRIPTION,
	 COUNT(eq.equip_ident) QUANTITY
FROM current_Equip_status CES 
	INNER JOIN EQUIP EQ on eq.equip_ident = CES.equip_ident 
	INNER JOIN FLEET FL on FL.flt_fleet_ident = eq.fleet_ident
where CES.STATUS_CODE = 'O04' AND fl.FLT_DESC = 'CAMIONES'


/**Número TOTAL DE CAMIONES**/
select
	GETDATE() 'CURRENT_TIMESTAMP',
	fl.flt_desc FLEET,
	COUNT(eq.equip_ident) QUANTITY
FROM current_Equip_status CES 
	INNER JOIN EQUIP EQ on eq.equip_ident = CES.equip_ident 
	INNER JOIN FLEET FL on FL.flt_fleet_ident = eq.fleet_ident
where EQ.EQUIP_IDENT LIKE 'T%' AND EQ.ACTIVE = 'Y'
GROUP BY eq.FLEET_IDENT, fl.FLT_DESC


/**Tiempo Promedio de la pala E822 cargando un camión **/
DECLARE @CURRENTLY_IDENT INT;
DECLARE @CSHIFT_DATE DATE;
SET  @CURRENTLY_IDENT = 
	CASE WHEN (DATEPART(HH, GETDATE()) BETWEEN 8 AND 19) THEN 1 ELSE 2 END;
SET @CSHIFT_DATE = 
	CASE WHEN (@CURRENTLY_IDENT = 2 AND (DATEPART(HH, GETDATE()) BETWEEN 0 AND 7)) 
	THEN CONVERT(date, dateadd(DD,-1,GETDATE()))
	ELSE CONVERT(date, GETDATE()) END;
SELECT
	GETDATE() 'CURRENT_TIMESTAMP',
	EST.SHIFT_DATE, 
	EST.SHIFT_IDENT, 
	'E822' EQUIP_IDENT, 
	'N13' STATUS_CODE, 
	'Pala Cargando' STATUS_DESC, 
	AVG_TIME = AVG((DATEDIFF(SECOND,EST.START_TIMESTAMP,EST.END_TIMESTAMP))/60.00)
FROM 
	EQUIPMENT_STATUS_TRANS EST 
WHERE EST.EQUIP_IDENT = 'E822' AND EST.STATUS_CODE = 'N13'
	--AND SHIFT_IDENT = @CURRENTLY_IDENT	--turno en el que se consulta
	--AND SHIFT_DATE = @CSHIFT_DATE		--fecha segun el turno en el que se consulta si
GROUP BY SHIFT_DATE, SHIFT_IDENT
ORDER BY SHIFT_DATE


/**Tiempo Promedio de la pala E838 cargando un camión **/
DECLARE @CURRENTLY_IDENT INT;
DECLARE @CSHIFT_DATE DATE;
SET  @CURRENTLY_IDENT = 
	CASE WHEN (DATEPART(HH, GETDATE()) BETWEEN 8 AND 19) THEN 1 ELSE 2 END;
SET @CSHIFT_DATE = 
	CASE WHEN (@CURRENTLY_IDENT = 2 AND (DATEPART(HH, GETDATE()) BETWEEN 0 AND 7)) 
	THEN CONVERT(date, dateadd(DD,-1,GETDATE()))
	ELSE CONVERT(date, GETDATE()) END;
SELECT 
	GETDATE() 'CURRENT_TIMESTAMP',
	EST.SHIFT_DATE, 
	EST.SHIFT_IDENT, 
	'E838' EQUIP_IDENT, 
	'N13' STATUS_CODE, 
	'Pala Cargando' STATUS_DESC, 
	AVG_TIME = AVG((DATEDIFF(SECOND,EST.START_TIMESTAMP,EST.END_TIMESTAMP))/60.00)
FROM 
	EQUIPMENT_STATUS_TRANS EST 
	WHERE EST.EQUIP_IDENT = 'E838' AND EST.STATUS_CODE = 'N13'
	--AND SHIFT_IDENT = @CURRENTLY_IDENT	--turno en el que se consulta
	--AND SHIFT_DATE = @CSHIFT_DATE			--fecha segun el turno en el que se consulta si
GROUP BY SHIFT_DATE, SHIFT_IDENT
ORDER BY SHIFT_DATE


